import { REPO } from "./constants";
import type { DuplicatePair, Issue, PR } from "./types";

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

function twoWeeksAgo(): string {
  const d = new Date();
  d.setUTCDate(d.getUTCDate() - 14);
  return d.toISOString().slice(0, 10);
}

function labelStr(labels: string[]): string {
  return labels.length > 0 ? labels.join(", ") : "—";
}

function moduleStr(modules: string[], cap = 4): string {
  if (modules.length === 0) return "—";
  if (modules.length <= cap) return modules.join(", ");
  return modules.slice(0, cap).join(", ") + `, +${modules.length - cap} more`;
}

/**
 * Markdown link to an issue/PR. GitHub redirects /issues/N to /pull/N
 * automatically when N is a PR, so one URL pattern covers both.
 */
function link(num: number, showHash = false): string {
  const label = showHash ? `#${num}` : String(num);
  return `[${label}](https://github.com/${REPO}/issues/${num})`;
}

function escapePipe(s: string): string {
  return s.replace(/\|/g, "\\|");
}

function byNumberDesc<T extends { number: number }>(rows: T[]): T[] {
  return [...rows].sort((a, b) => b.number - a.number);
}

function issueRow(i: Issue): string {
  return (
    `| ${link(i.number)} | ${escapePipe(i.title)} | ${i.author} | ` +
    `${i.created_at.slice(0, 10)} | ${labelStr(i.labels)} | ${moduleStr(i.modules)} |`
  );
}

function prRow(pr: PR): string {
  const linked =
    pr.linked_issues.length > 0
      ? pr.linked_issues.map((n) => link(n, true)).join(", ")
      : "—";
  return (
    `| ${link(pr.number, true)} | \`${pr.branch}\` | ` +
    `${escapePipe(pr.title)} | ${linked} |`
  );
}

export function renderMarkdown(
  issues: Issue[],
  prs: PR[],
  dupes: DuplicatePair[],
): string {
  const openIssues = issues.filter((i) => i.state === "OPEN");
  const closedIssues = issues.filter((i) => i.state === "CLOSED");
  const openPrs = prs.filter((p) => p.state === "OPEN");
  const mergedPrs = prs.filter((p) => p.state === "MERGED");

  const cutoff = twoWeeksAgo();
  const recentClosed = closedIssues.filter((i) => (i.closed_at ?? "") >= cutoff);
  const recentMerged = mergedPrs.filter((p) => (p.merged_at ?? "") >= cutoff);

  // Noise items are triaged in their own section; exclude them from CRITICAL
  // and HIGH so the actionable queues aren't polluted by fear-posts or spam
  // that happen to ship keyword collisions in their bodies.
  const critical = openIssues.filter(
    (i) => i.severity === "critical" && !i.is_noise,
  );
  const high = openIssues.filter((i) => i.severity === "high" && !i.is_noise);
  const bugsLabeled = openIssues.filter((i) => i.labels.includes("bug"));
  const bugsUnlabeledDefects = openIssues.filter(
    (i) =>
      !i.labels.includes("bug") &&
      (i.severity === "critical" || i.severity === "high") &&
      !i.is_noise,
  );
  const featsLabeled = openIssues.filter((i) => i.labels.includes("enhancement"));
  const noise = openIssues.filter((i) => i.is_noise);
  const suspiciousPrs = openPrs.filter((p) => p.suspicious_flags.length > 0);

  const lines: string[] = [];
  lines.push("# MemPalace Issue Tracker\n");
  lines.push(
    `> Synced from [${REPO}](https://github.com/${REPO}/issues) on ${today()}`,
  );
  lines.push(
    `> Total: **${openIssues.length} open issues**, **${openPrs.length} open PRs**\n`,
  );
  lines.push(
    "> Generated by the triage module — personal triage tool (not for upstream).\n",
  );

  // ─── CRITICAL ──────────────────────────────────────────────────────────────
  lines.push("---\n");
  lines.push("## CRITICAL (heuristic)\n");
  lines.push(
    "Auto-classified by keyword match: crash / corruption / data-loss / " +
      "security in title or body. Review and promote to hand-curated list as " +
      "needed.\n",
  );
  lines.push("| # | Title | Author | Filed | Labels | Modules |");
  lines.push("|---|---|---|---|---|---|");
  for (const i of byNumberDesc(critical)) lines.push(issueRow(i));
  lines.push("");

  // ─── HIGH ──────────────────────────────────────────────────────────────────
  lines.push("## HIGH (heuristic)\n");
  lines.push(
    "Silent failures, memory exhaustion, race conditions, stale state.\n",
  );
  lines.push("| # | Title | Author | Filed | Labels | Modules |");
  lines.push("|---|---|---|---|---|---|");
  for (const i of byNumberDesc(high)) lines.push(issueRow(i));
  lines.push("");

  // ─── Bugs (labeled) ────────────────────────────────────────────────────────
  lines.push(`## Bugs — labeled \`bug\` (${bugsLabeled.length} open)\n`);
  lines.push("| # | Title | Author | Filed | Severity | Modules |");
  lines.push("|---|---|---|---|---|---|");
  for (const i of byNumberDesc(bugsLabeled)) {
    lines.push(
      `| ${link(i.number)} | ${escapePipe(i.title)} | ${i.author} | ` +
        `${i.created_at.slice(0, 10)} | ${i.severity} | ${moduleStr(i.modules)} |`,
    );
  }
  lines.push("");

  // ─── Bugs (unlabeled but clearly defects) ─────────────────────────────────
  lines.push(
    `## Bugs — unlabeled but severity ≥ high (${bugsUnlabeledDefects.length})\n`,
  );
  lines.push(
    "Unambiguous defects the heuristic flagged but upstream hasn't " +
      "labeled. Candidates for `bug` label.\n",
  );
  lines.push("| # | Title | Filed | Severity | Modules |");
  lines.push("|---|---|---|---|---|");
  for (const i of byNumberDesc(bugsUnlabeledDefects)) {
    lines.push(
      `| ${link(i.number)} | ${escapePipe(i.title)} | ` +
        `${i.created_at.slice(0, 10)} | ${i.severity} | ${moduleStr(i.modules)} |`,
    );
  }
  lines.push("");

  // ─── Features ──────────────────────────────────────────────────────────────
  lines.push(
    `## Features — labeled \`enhancement\` (${featsLabeled.length} open)\n`,
  );
  lines.push("| # | Title | Author | Filed |");
  lines.push("|---|---|---|---|");
  for (const i of byNumberDesc(featsLabeled)) {
    lines.push(
      `| ${link(i.number)} | ${escapePipe(i.title)} | ${i.author} | ` +
        `${i.created_at.slice(0, 10)} |`,
    );
  }
  lines.push("");

  // ─── Noise ─────────────────────────────────────────────────────────────────
  lines.push(`## Low-signal / noise candidates (${noise.length})\n`);
  lines.push(
    "Auto-flagged as low-value. Review before closing — heuristic only.\n",
  );
  lines.push("| # | Title | Reason |");
  lines.push("|---|---|---|");
  for (const i of byNumberDesc(noise)) {
    lines.push(
      `| ${link(i.number)} | ${escapePipe(i.title)} | ${i.noise_reason} |`,
    );
  }
  lines.push("");

  // ─── Near-duplicate issues ─────────────────────────────────────────────────
  if (dupes.length > 0) {
    lines.push(`## Near-duplicate open issues (${dupes.length} pairs)\n`);
    lines.push("Pairs with title similarity > 0.85. Review for consolidation.\n");
    lines.push("| # A | # B | Similarity |");
    lines.push("|---|---|---|");
    for (const d of [...dupes].sort((x, y) => y.similarity - x.similarity)) {
      lines.push(
        `| ${link(d.a)} | ${link(d.b)} | ${d.similarity.toFixed(2)} |`,
      );
    }
    lines.push("");
  }

  // ─── Suspicious PRs ────────────────────────────────────────────────────────
  lines.push(`## PRs flagged for review (${suspiciousPrs.length})\n`);
  lines.push(
    "PRs matching one or more suspicion heuristics. Most flags are " +
      "benign — review individually before acting. Flags are informational.\n",
  );
  for (const pr of byNumberDesc(suspiciousPrs)) {
    lines.push(
      `- **${link(pr.number, true)}** [\`${pr.branch}\`] ` +
        `by @${pr.author} (+${pr.additions}/-${pr.deletions}) — ${pr.title}`,
    );
    for (const flag of pr.suspicious_flags) lines.push(`  - ! ${flag}`);
    for (const note of pr.context_notes) lines.push(`  - · ${note}`);
  }
  lines.push("");

  // ─── Recently merged ───────────────────────────────────────────────────────
  lines.push(`## Recently merged (${recentMerged.length}, last 14 days)\n`);
  lines.push("| # | Branch | Title | Merged | Modules |");
  lines.push("|---|---|---|---|---|");
  const mergedSorted = [...recentMerged].sort((a, b) =>
    (b.merged_at ?? "").localeCompare(a.merged_at ?? ""),
  );
  for (const pr of mergedSorted) {
    lines.push(
      `| ${link(pr.number, true)} | \`${pr.branch}\` | ` +
        `${escapePipe(pr.title)} | ${(pr.merged_at ?? "").slice(0, 10)} | ` +
        `${moduleStr(pr.modules)} |`,
    );
  }
  lines.push("");

  // ─── Recently closed issues ────────────────────────────────────────────────
  lines.push(`## Recently closed (${recentClosed.length}, last 14 days)\n`);
  lines.push("| # | Title | Labels | Closed |");
  lines.push("|---|---|---|---|");
  const closedSorted = [...recentClosed].sort((a, b) =>
    (b.closed_at ?? "").localeCompare(a.closed_at ?? ""),
  );
  for (const i of closedSorted) {
    lines.push(
      `| ${link(i.number)} | ${escapePipe(i.title)} | ` +
        `${labelStr(i.labels)} | ${(i.closed_at ?? "").slice(0, 10)} |`,
    );
  }
  lines.push("");

  // ─── Summary ───────────────────────────────────────────────────────────────
  lines.push("## Summary\n");
  lines.push("| Category | Count |");
  lines.push("|---|---|");
  lines.push(`| Open issues | ${openIssues.length} |`);
  lines.push(`|   of which CRITICAL (heuristic) | ${critical.length} |`);
  lines.push(`|   of which HIGH (heuristic) | ${high.length} |`);
  lines.push(`|   of which labeled \`bug\` | ${bugsLabeled.length} |`);
  lines.push(`|   of which labeled \`enhancement\` | ${featsLabeled.length} |`);
  lines.push(`|   of which noise candidates | ${noise.length} |`);
  lines.push(`| Open PRs | ${openPrs.length} |`);
  lines.push(`|   of which flagged for review | ${suspiciousPrs.length} |`);
  lines.push(`| Merged (last 14d) | ${recentMerged.length} |`);
  lines.push(`| Closed issues (last 14d) | ${recentClosed.length} |`);
  lines.push("");

  return lines.join("\n");
}
